---
title: "Crosstech Solutions Group"
subtitle: "Публикационная активность компании на Хабре"
author: "Назаровская Вероника"
date: today
format: html
editor: visual
lang: ru
toc: true
number-sections: false
theme: minty
link-external-newwindow: true
embed-resources: true
standalone: true
---

## О компании

[**Crosstech Solutions Group**](https://ct-sg.ru/) (далее – **CTSG/КТСГ**) – российский разработчик инновационных решений для комплексной защиты информации бизнеса. Компания предлагает готовые решения, осуществляет заказную разработку и предоставляет ИТ-услуги в области кибербезопасности. Представлена на рынке ИБ с 2018 года. Продуктовый портфель КТСГ на сегодняшний день насчитывает 11 продуктов. Все они разработаны на основе глубоких исследований рынка информационной безопасности и закрепили за собой статус высокоэффективных средств защиты информации, пройдя апробацию в крупнейших компаниях различных отраслей экономики России. ИБ-продукты включены в реестр отечественного ПО Минцифры России и рекомендованы для импортозамещения на российских предприятиях.

Компания активно развивается не только со стороны разработки и поставки ПО, но и со стороны PR и маркетинга. Так, компания ведет соц. сети для повышения узнаваемости продуктов и развития бренда:

-   [Telegram-канал](https://t.me/ctsg_news);
-   [группа ВКонтакте](https://vk.com/ctsg_news);
-   [Хабр](https://habr.com/ru/companies/ctsg/articles/) и др.

## Цель исследования

В рамках учебной работы представлен анализ публикационной активности компании на Хабре. Здесь я рассмотрела

```{r}
1 + 1
```
